//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CultRes {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsRes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATIS.Ui.CultRes.StringsRes", typeof(StringsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quit application ? ähnelt.
        /// </summary>
        public static string AppClose {
            get {
                return ResourceManager.GetString("AppClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application closed ähnelt.
        /// </summary>
        public static string AppClosed {
            get {
                return ResourceManager.GetString("AppClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you really shure to close this application ähnelt.
        /// </summary>
        public static string AppCloseQuestion {
            get {
                return ResourceManager.GetString("AppCloseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        public static string AppCloseQuestion1 {
            get {
                return ResourceManager.GetString("AppCloseQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Request for principal permission failed ähnelt.
        /// </summary>
        public static string AreaAuthMessage {
            get {
                return ResourceManager.GetString("AreaAuthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You don&apos;t have authorization for this area ähnelt.
        /// </summary>
        public static string AreaAuthNo {
            get {
                return ResourceManager.GetString("AreaAuthNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Access denied. Please provide some valid credentials. ähnelt.
        /// </summary>
        public static string AuthAccessNot {
            get {
                return ResourceManager.GetString("AuthAccessNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom authentication ähnelt.
        /// </summary>
        public static string AuthCustom {
            get {
                return ResourceManager.GetString("AuthCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are not authorized! ähnelt.
        /// </summary>
        public static string AuthNot {
            get {
                return ResourceManager.GetString("AuthNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not authenticated! ähnelt.
        /// </summary>
        public static string AuthUserNot {
            get {
                return ResourceManager.GetString("AuthUserNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signed in as {0}. {1} ähnelt.
        /// </summary>
        public static string AuthUserQuestion {
            get {
                return ResourceManager.GetString("AuthUserQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are an administrator! ähnelt.
        /// </summary>
        public static string AuthUserQuestion1 {
            get {
                return ResourceManager.GetString("AuthUserQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are NOT a member of the administrators group. ähnelt.
        /// </summary>
        public static string AuthUserQuestion2 {
            get {
                return ResourceManager.GetString("AuthUserQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Option must be checked ähnelt.
        /// </summary>
        public static string CheckOption {
            get {
                return ResourceManager.GetString("CheckOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Class ähnelt.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comment ähnelt.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die include connected datasets, not possible to delete here ! ähnelt.
        /// </summary>
        public static string ConnectedDataset {
            get {
                return ResourceManager.GetString("ConnectedDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connected Table ähnelt.
        /// </summary>
        public static string ConnectedTable {
            get {
                return ResourceManager.GetString("ConnectedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t convert back ähnelt.
        /// </summary>
        public static string ConvertBackNo {
            get {
                return ResourceManager.GetString("ConvertBackNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Country ähnelt.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die dataset already existing ähnelt.
        /// </summary>
        public static string DatasetExist {
            get {
                return ResourceManager.GetString("DatasetExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die new ähnelt.
        /// </summary>
        public static string DatasetNew {
            get {
                return ResourceManager.GetString("DatasetNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No dataset found ähnelt.
        /// </summary>
        public static string DatasetNot {
            get {
                return ResourceManager.GetString("DatasetNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die dataset not found ähnelt.
        /// </summary>
        public static string DatasetNotExist {
            get {
                return ResourceManager.GetString("DatasetNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please Select dataset ! ähnelt.
        /// </summary>
        public static string DatasetSelect {
            get {
                return ResourceManager.GetString("DatasetSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only ähnelt.
        /// </summary>
        public static string DeleteCan {
            get {
                return ResourceManager.GetString("DeleteCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die can be deleted ! ähnelt.
        /// </summary>
        public static string DeleteCan1 {
            get {
                return ResourceManager.GetString("DeleteCan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dataset not to delete ähnelt.
        /// </summary>
        public static string DeleteNot {
            get {
                return ResourceManager.GetString("DeleteNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you really shure to delete this  ähnelt.
        /// </summary>
        public static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        public static string DeleteQuestion1 {
            get {
                return ResourceManager.GetString("DeleteQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die was successfully deleted ähnelt.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Division ähnelt.
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die eMail does&apos;t exist ähnelt.
        /// </summary>
        public static string EMailNotExist {
            get {
                return ResourceManager.GetString("EMailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to save ähnelt.
        /// </summary>
        public static string FailedToSave {
            get {
                return ResourceManager.GetString("FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Family ähnelt.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FiSpecies ähnelt.
        /// </summary>
        public static string FiSpecies {
            get {
                return ResourceManager.GetString("FiSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Genus ähnelt.
        /// </summary>
        public static string Genus {
            get {
                return ResourceManager.GetString("Genus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geographic ähnelt.
        /// </summary>
        public static string Geographic {
            get {
                return ResourceManager.GetString("Geographic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get new ID ähnelt.
        /// </summary>
        public static string GetNewNumber {
            get {
                return ResourceManager.GetString("GetNewNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Illegal characters or  ähnelt.
        /// </summary>
        public static string IllegalCharacters {
            get {
                return ResourceManager.GetString("IllegalCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image ähnelt.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infraclass ähnelt.
        /// </summary>
        public static string Infraclass {
            get {
                return ResourceManager.GetString("Infraclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infrafamily ähnelt.
        /// </summary>
        public static string Infrafamily {
            get {
                return ResourceManager.GetString("Infrafamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infraordo ähnelt.
        /// </summary>
        public static string Infraordo {
            get {
                return ResourceManager.GetString("Infraordo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infratribus ähnelt.
        /// </summary>
        public static string Infratribus {
            get {
                return ResourceManager.GetString("Infratribus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input requested ähnelt.
        /// </summary>
        public static string InputRequested {
            get {
                return ResourceManager.GetString("InputRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid date ähnelt.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legio ähnelt.
        /// </summary>
        public static string Legio {
            get {
                return ResourceManager.GetString("Legio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List ähnelt.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die is an administrator ähnelt.
        /// </summary>
        public static string LoginAdministrator {
            get {
                return ResourceManager.GetString("LoginAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die is logged in as  ähnelt.
        /// </summary>
        public static string LoginAs {
            get {
                return ResourceManager.GetString("LoginAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die is a biologist ähnelt.
        /// </summary>
        public static string LoginBiologist {
            get {
                return ResourceManager.GetString("LoginBiologist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The application&apos;s default thread principal must be set to a CustomPrincipal object on startup. ähnelt.
        /// </summary>
        public static string LoginCustomPrincipal {
            get {
                return ResourceManager.GetString("LoginCustomPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die is a developer ähnelt.
        /// </summary>
        public static string LoginDeveloper {
            get {
                return ResourceManager.GetString("LoginDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter an email. ähnelt.
        /// </summary>
        public static string LoginEmail {
            get {
                return ResourceManager.GetString("LoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ERROR: {0} ähnelt.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login failed! Please provide some valid credentials. ähnelt.
        /// </summary>
        public static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The underlying provider failed on open ähnelt.
        /// </summary>
        public static string LoginFailEx {
            get {
                return ResourceManager.GetString("LoginFailEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die is an user ähnelt.
        /// </summary>
        public static string LoginUser {
            get {
                return ResourceManager.GetString("LoginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a valid email. ähnelt.
        /// </summary>
        public static string LoginValidEmail {
            get {
                return ResourceManager.GetString("LoginValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry! Please enter existing Email/Password. ähnelt.
        /// </summary>
        public static string LoginValidEmailPassword {
            get {
                return ResourceManager.GetString("LoginValidEmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid password ähnelt.
        /// </summary>
        public static string LoginValidPassword {
            get {
                return ResourceManager.GetString("LoginValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die is a zoologist ähnelt.
        /// </summary>
        public static string LoginZoologist {
            get {
                return ResourceManager.GetString("LoginZoologist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nobody logged in ähnelt.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string MainWindowAbout {
            get {
                return ResourceManager.GetString("MainWindowAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adjustment ähnelt.
        /// </summary>
        public static string MainWindowAdjustment {
            get {
                return ResourceManager.GetString("MainWindowAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Admin Area ähnelt.
        /// </summary>
        public static string MainWindowAdminArea {
            get {
                return ResourceManager.GetString("MainWindowAdminArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Appearence ähnelt.
        /// </summary>
        public static string MainWindowAppearence {
            get {
                return ResourceManager.GetString("MainWindowAppearence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database ähnelt.
        /// </summary>
        public static string MainWindowDatabase {
            get {
                return ResourceManager.GetString("MainWindowDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downsize ähnelt.
        /// </summary>
        public static string MainWindowDownsize {
            get {
                return ResourceManager.GetString("MainWindowDownsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feedback ähnelt.
        /// </summary>
        public static string MainWindowFeedback {
            get {
                return ResourceManager.GetString("MainWindowFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string MainWindowHome {
            get {
                return ResourceManager.GetString("MainWindowHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info Area ähnelt.
        /// </summary>
        public static string MainWindowInfoArea {
            get {
                return ResourceManager.GetString("MainWindowInfoArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string MainWindowLanguage {
            get {
                return ResourceManager.GetString("MainWindowLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximize ähnelt.
        /// </summary>
        public static string MainWindowMaximize {
            get {
                return ResourceManager.GetString("MainWindowMaximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Area ähnelt.
        /// </summary>
        public static string MainWindowUserArea {
            get {
                return ResourceManager.GetString("MainWindowUserArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot connection to the Sql Server service on MySqlServer ähnelt.
        /// </summary>
        public static string NoConnectServer {
            get {
                return ResourceManager.GetString("NoConnectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordo ähnelt.
        /// </summary>
        public static string Ordo {
            get {
                return ResourceManager.GetString("Ordo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Phylum ähnelt.
        /// </summary>
        public static string Phylum {
            get {
                return ResourceManager.GetString("Phylum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PlSpecies ähnelt.
        /// </summary>
        public static string PlSpecies {
            get {
                return ResourceManager.GetString("PlSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference Author ähnelt.
        /// </summary>
        public static string RefAuthor {
            get {
                return ResourceManager.GetString("RefAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference ähnelt.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference Author ähnelt.
        /// </summary>
        public static string ReferenceAuthor {
            get {
                return ResourceManager.GetString("ReferenceAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference Expert ähnelt.
        /// </summary>
        public static string ReferenceExpert {
            get {
                return ResourceManager.GetString("ReferenceExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference Source ähnelt.
        /// </summary>
        public static string ReferenceSource {
            get {
                return ResourceManager.GetString("ReferenceSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference Expert ähnelt.
        /// </summary>
        public static string RefExpert {
            get {
                return ResourceManager.GetString("RefExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference Source ähnelt.
        /// </summary>
        public static string RefSource {
            get {
                return ResourceManager.GetString("RefSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kingdom ähnelt.
        /// </summary>
        public static string Regnum {
            get {
                return ResourceManager.GetString("Regnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report ähnelt.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Acquired ähnelt.
        /// </summary>
        public static string ReportAcquired {
            get {
                return ResourceManager.GetString("ReportAcquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Address ähnelt.
        /// </summary>
        public static string ReportAddress {
            get {
                return ResourceManager.GetString("ReportAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Article/Chapter Title ähnelt.
        /// </summary>
        public static string ReportArticleTitle {
            get {
                return ResourceManager.GetString("ReportArticleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Author ähnelt.
        /// </summary>
        public static string ReportAuthor {
            get {
                return ResourceManager.GetString("ReportAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Author(s)/Editor(s) ähnelt.
        /// </summary>
        public static string ReportAuthorsEditors {
            get {
                return ResourceManager.GetString("ReportAuthorsEditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Basinheight ähnelt.
        /// </summary>
        public static string ReportBasinHeight {
            get {
                return ResourceManager.GetString("ReportBasinHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Basinlength ähnelt.
        /// </summary>
        public static string ReportBasinLength {
            get {
                return ResourceManager.GetString("ReportBasinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Journal/Book Name ähnelt.
        /// </summary>
        public static string ReportBookName {
            get {
                return ResourceManager.GetString("ReportBookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CarboHardness (°KH) ähnelt.
        /// </summary>
        public static string ReportCarboHardness12 {
            get {
                return ResourceManager.GetString("ReportCarboHardness12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comment(s) ähnelt.
        /// </summary>
        public static string ReportComments {
            get {
                return ResourceManager.GetString("ReportComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Common Name(s) ähnelt.
        /// </summary>
        public static string ReportCommonNames {
            get {
                return ResourceManager.GetString("ReportCommonNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continent ähnelt.
        /// </summary>
        public static string ReportContinent {
            get {
                return ResourceManager.GetString("ReportContinent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Country ähnelt.
        /// </summary>
        public static string ReportCountry {
            get {
                return ResourceManager.GetString("ReportCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Culture ähnelt.
        /// </summary>
        public static string ReportCulture {
            get {
                return ResourceManager.GetString("ReportCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Standing ähnelt.
        /// </summary>
        public static string ReportCurrentStand {
            get {
                return ResourceManager.GetString("ReportCurrentStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Quality Indicators ähnelt.
        /// </summary>
        public static string ReportDataQualiIndicator {
            get {
                return ResourceManager.GetString("ReportDataQualiIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Species for Beginners ähnelt.
        /// </summary>
        public static string ReportDifficult1 {
            get {
                return ResourceManager.GetString("ReportDifficult1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Species for Beginners with experience ähnelt.
        /// </summary>
        public static string ReportDifficult2 {
            get {
                return ResourceManager.GetString("ReportDifficult2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Species for advanced Beginners ähnelt.
        /// </summary>
        public static string ReportDifficult3 {
            get {
                return ResourceManager.GetString("ReportDifficult3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Species for Experts ähnelt.
        /// </summary>
        public static string ReportDifficult4 {
            get {
                return ResourceManager.GetString("ReportDifficult4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Direct Children ähnelt.
        /// </summary>
        public static string ReportDirectChild {
            get {
                return ResourceManager.GetString("ReportDirectChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [English] ähnelt.
        /// </summary>
        public static string ReportEnglish {
            get {
                return ResourceManager.GetString("ReportEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expert ähnelt.
        /// </summary>
        public static string ReportExpert {
            get {
                return ResourceManager.GetString("ReportExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expert(s) ähnelt.
        /// </summary>
        public static string ReportExperts {
            get {
                return ResourceManager.GetString("ReportExperts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fishlength ähnelt.
        /// </summary>
        public static string ReportFishLength {
            get {
                return ResourceManager.GetString("ReportFishLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Food ähnelt.
        /// </summary>
        public static string ReportFood {
            get {
                return ResourceManager.GetString("ReportFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [French] ähnelt.
        /// </summary>
        public static string ReportFrench {
            get {
                return ResourceManager.GetString("ReportFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die generated at   ähnelt.
        /// </summary>
        public static string ReportGenerated {
            get {
                return ResourceManager.GetString("ReportGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geographics ähnelt.
        /// </summary>
        public static string ReportGeographics {
            get {
                return ResourceManager.GetString("ReportGeographics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [German] ähnelt.
        /// </summary>
        public static string ReportGerman {
            get {
                return ResourceManager.GetString("ReportGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Global ähnelt.
        /// </summary>
        public static string ReportGlobal {
            get {
                return ResourceManager.GetString("ReportGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Global Species Completeness ähnelt.
        /// </summary>
        public static string ReportGlobalSpecComp {
            get {
                return ResourceManager.GetString("ReportGlobalSpecComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sexual dimorphism ähnelt.
        /// </summary>
        public static string ReportGu {
            get {
                return ResourceManager.GetString("ReportGu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hardness (°dGH) ähnelt.
        /// </summary>
        public static string ReportHardness12 {
            get {
                return ResourceManager.GetString("ReportHardness12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Herbivore ähnelt.
        /// </summary>
        public static string ReportHerbivore {
            get {
                return ResourceManager.GetString("ReportHerbivore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Http ähnelt.
        /// </summary>
        public static string ReportHttp {
            get {
                return ResourceManager.GetString("ReportHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Husbandry ähnelt.
        /// </summary>
        public static string ReportHusbandry {
            get {
                return ResourceManager.GetString("ReportHusbandry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mime Type ähnelt.
        /// </summary>
        public static string ReportImageMimeType {
            get {
                return ResourceManager.GetString("ReportImageMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images ähnelt.
        /// </summary>
        public static string ReportImages {
            get {
                return ResourceManager.GetString("ReportImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shot Date ähnelt.
        /// </summary>
        public static string ReportImageShot {
            get {
                return ResourceManager.GetString("ReportImageShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Importer/Year ähnelt.
        /// </summary>
        public static string ReportImporterWithYear {
            get {
                return ResourceManager.GetString("ReportImporterWithYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        public static string ReportInfo {
            get {
                return ResourceManager.GetString("ReportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ISBN/ISSN ähnelt.
        /// </summary>
        public static string ReportIsbn {
            get {
                return ResourceManager.GetString("ReportIsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Karnivore ähnelt.
        /// </summary>
        public static string ReportKarnivore {
            get {
                return ResourceManager.GetString("ReportKarnivore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latitude ähnelt.
        /// </summary>
        public static string ReportLatitude {
            get {
                return ResourceManager.GetString("ReportLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latitude - Longitude ähnelt.
        /// </summary>
        public static string ReportLatitudeLongitude {
            get {
                return ResourceManager.GetString("ReportLatitudeLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LDA-Number/LDA-Origin ähnelt.
        /// </summary>
        public static string ReportLdaNumberLdaOrigin {
            get {
                return ResourceManager.GetString("ReportLdaNumberLdaOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Limnivore ähnelt.
        /// </summary>
        public static string ReportLimnivore {
            get {
                return ResourceManager.GetString("ReportLimnivore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die L-Number/L-Origin ähnelt.
        /// </summary>
        public static string ReportLNumberLOrigin {
            get {
                return ResourceManager.GetString("ReportLNumberLOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Longitude ähnelt.
        /// </summary>
        public static string ReportLongitude {
            get {
                return ResourceManager.GetString("ReportLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Memo ähnelt.
        /// </summary>
        public static string ReportMemo {
            get {
                return ResourceManager.GetString("ReportMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Memo Culture ähnelt.
        /// </summary>
        public static string ReportMemoCulture {
            get {
                return ResourceManager.GetString("ReportMemoCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Memo Dimorphism ähnelt.
        /// </summary>
        public static string ReportMemoDimorphism {
            get {
                return ResourceManager.GetString("ReportMemoDimorphism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Memo Food ähnelt.
        /// </summary>
        public static string ReportMemoFood {
            get {
                return ResourceManager.GetString("ReportMemoFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Memo Global ähnelt.
        /// </summary>
        public static string ReportMemoGlobal {
            get {
                return ResourceManager.GetString("ReportMemoGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Memo Reproduction ähnelt.
        /// </summary>
        public static string ReportMemoReproduction {
            get {
                return ResourceManager.GetString("ReportMemoReproduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Memo Special ähnelt.
        /// </summary>
        public static string ReportMemoSpecial {
            get {
                return ResourceManager.GetString("ReportMemoSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Memo Species ähnelt.
        /// </summary>
        public static string ReportMemoSpecies {
            get {
                return ResourceManager.GetString("ReportMemoSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Memo Technic ähnelt.
        /// </summary>
        public static string ReportMemoTechnic {
            get {
                return ResourceManager.GetString("ReportMemoTechnic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name(s) ähnelt.
        /// </summary>
        public static string ReportNames {
            get {
                return ResourceManager.GetString("ReportNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notes ähnelt.
        /// </summary>
        public static string ReportNotes {
            get {
                return ResourceManager.GetString("ReportNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Omnivore ähnelt.
        /// </summary>
        public static string ReportOmnivore {
            get {
                return ResourceManager.GetString("ReportOmnivore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other Source(s) ähnelt.
        /// </summary>
        public static string ReportOtherSources {
            get {
                return ResourceManager.GetString("ReportOtherSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page(s) ähnelt.
        /// </summary>
        public static string ReportPages {
            get {
                return ResourceManager.GetString("ReportPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ph Values ähnelt.
        /// </summary>
        public static string ReportPh12 {
            get {
                return ResourceManager.GetString("ReportPh12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plantlength ähnelt.
        /// </summary>
        public static string ReportPlantLength {
            get {
                return ResourceManager.GetString("ReportPlantLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [Portuguese] ähnelt.
        /// </summary>
        public static string ReportPortuguese {
            get {
                return ResourceManager.GetString("ReportPortuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Publication Date ähnelt.
        /// </summary>
        public static string ReportPublicationDate {
            get {
                return ResourceManager.GetString("ReportPublicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Publication Place ähnelt.
        /// </summary>
        public static string ReportPublicationPlace {
            get {
                return ResourceManager.GetString("ReportPublicationPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Publication(s) ähnelt.
        /// </summary>
        public static string ReportPublications {
            get {
                return ResourceManager.GetString("ReportPublications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Publisher ähnelt.
        /// </summary>
        public static string ReportPublisher {
            get {
                return ResourceManager.GetString("ReportPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Record Credibility Rating ähnelt.
        /// </summary>
        public static string ReportRecordCrediRate {
            get {
                return ResourceManager.GetString("ReportRecordCrediRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latest Record Review ähnelt.
        /// </summary>
        public static string ReportRecordUpdate {
            get {
                return ResourceManager.GetString("ReportRecordUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die References ähnelt.
        /// </summary>
        public static string ReportReferences {
            get {
                return ResourceManager.GetString("ReportReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference for ähnelt.
        /// </summary>
        public static string ReportRefFor {
            get {
                return ResourceManager.GetString("ReportRefFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bottom ähnelt.
        /// </summary>
        public static string ReportRegionBottom {
            get {
                return ResourceManager.GetString("ReportRegionBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Middle ähnelt.
        /// </summary>
        public static string ReportRegionMiddle {
            get {
                return ResourceManager.GetString("ReportRegionMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top ähnelt.
        /// </summary>
        public static string ReportRegionTop {
            get {
                return ResourceManager.GetString("ReportRegionTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reproduction ähnelt.
        /// </summary>
        public static string ReportReproduction {
            get {
                return ResourceManager.GetString("ReportReproduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source ähnelt.
        /// </summary>
        public static string ReportSource {
            get {
                return ResourceManager.GetString("ReportSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Social behavior ähnelt.
        /// </summary>
        public static string ReportSozial {
            get {
                return ResourceManager.GetString("ReportSozial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [Spanish] ähnelt.
        /// </summary>
        public static string ReportSpanish {
            get {
                return ResourceManager.GetString("ReportSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Synonym(s) ähnelt.
        /// </summary>
        public static string ReportSynonyms {
            get {
                return ResourceManager.GetString("ReportSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taxonomic Hierachy ähnelt.
        /// </summary>
        public static string ReportTaxoHiera {
            get {
                return ResourceManager.GetString("ReportTaxoHiera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taxonomy and Nomenclature ähnelt.
        /// </summary>
        public static string ReportTaxoNomen {
            get {
                return ResourceManager.GetString("ReportTaxoNomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taxonomic Serial No. ähnelt.
        /// </summary>
        public static string ReportTaxonomicId {
            get {
                return ResourceManager.GetString("ReportTaxonomicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taxonomic Rank ähnelt.
        /// </summary>
        public static string ReportTaxoRank {
            get {
                return ResourceManager.GetString("ReportTaxoRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taxonomic Status ähnelt.
        /// </summary>
        public static string ReportTaxoStatus {
            get {
                return ResourceManager.GetString("ReportTaxoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Technic ähnelt.
        /// </summary>
        public static string ReportTechnic {
            get {
                return ResourceManager.GetString("ReportTechnic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature (°C) ähnelt.
        /// </summary>
        public static string ReportTemp12 {
            get {
                return ResourceManager.GetString("ReportTemp12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aquaristic Taxonomic Information System ähnelt.
        /// </summary>
        public static string ReportTitle {
            get {
                return ResourceManager.GetString("ReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tradename ähnelt.
        /// </summary>
        public static string ReportTradeName {
            get {
                return ResourceManager.GetString("ReportTradeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Valid ähnelt.
        /// </summary>
        public static string ReportValid {
            get {
                return ResourceManager.GetString("ReportValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Year ähnelt.
        /// </summary>
        public static string ReportValidYear {
            get {
                return ResourceManager.GetString("ReportValidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ZoomLevel ähnelt.
        /// </summary>
        public static string ReportZoomLevel {
            get {
                return ResourceManager.GetString("ReportZoomLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application Name is required ähnelt.
        /// </summary>
        public static string RequiredApplicationName {
            get {
                return ResourceManager.GetString("RequiredApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Class Name is required  ähnelt.
        /// </summary>
        public static string RequiredClassName {
            get {
                return ResourceManager.GetString("RequiredClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select in Combobox ähnelt.
        /// </summary>
        public static string RequiredComboSelect {
            get {
                return ResourceManager.GetString("RequiredComboSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counter is required  ähnelt.
        /// </summary>
        public static string RequiredCounterName {
            get {
                return ResourceManager.GetString("RequiredCounterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Count ID is required  ähnelt.
        /// </summary>
        public static string RequiredCountID {
            get {
                return ResourceManager.GetString("RequiredCountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Division Name is required  ähnelt.
        /// </summary>
        public static string RequiredDivisionName {
            get {
                return ResourceManager.GetString("RequiredDivisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email is a required field. ähnelt.
        /// </summary>
        public static string RequiredEMail {
            get {
                return ResourceManager.GetString("RequiredEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email must contain be formated like so; xxx@xxx.xxx and contain no more then 50 characters. ähnelt.
        /// </summary>
        public static string RequiredEMail1 {
            get {
                return ResourceManager.GetString("RequiredEMail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email must formated like so; xxx@xxx.xxx ähnelt.
        /// </summary>
        public static string RequiredEMail2 {
            get {
                return ResourceManager.GetString("RequiredEMail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Family Name is required  ähnelt.
        /// </summary>
        public static string RequiredFamilyName {
            get {
                return ResourceManager.GetString("RequiredFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fisch Species Name is required  ähnelt.
        /// </summary>
        public static string RequiredFiSpeciesName {
            get {
                return ResourceManager.GetString("RequiredFiSpeciesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Future date required ähnelt.
        /// </summary>
        public static string RequiredFutureDate {
            get {
                return ResourceManager.GetString("RequiredFutureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select Genealogy Connect ähnelt.
        /// </summary>
        public static string RequiredGenealogyConnect {
            get {
                return ResourceManager.GetString("RequiredGenealogyConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Genus Name is required  ähnelt.
        /// </summary>
        public static string RequiredGenusName {
            get {
                return ResourceManager.GetString("RequiredGenusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infra Class Name is required  ähnelt.
        /// </summary>
        public static string RequiredInfraclassName {
            get {
                return ResourceManager.GetString("RequiredInfraclassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infra Family Name is required  ähnelt.
        /// </summary>
        public static string RequiredInfrafamilyName {
            get {
                return ResourceManager.GetString("RequiredInfrafamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infra Order Name is required  ähnelt.
        /// </summary>
        public static string RequiredInfraordoName {
            get {
                return ResourceManager.GetString("RequiredInfraordoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infra Tribus Name is required  ähnelt.
        /// </summary>
        public static string RequiredInfratribusName {
            get {
                return ResourceManager.GetString("RequiredInfratribusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input required ! ähnelt.
        /// </summary>
        public static string RequiredInput {
            get {
                return ResourceManager.GetString("RequiredInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Super Order Name is required  ähnelt.
        /// </summary>
        public static string RequiredLegioName {
            get {
                return ResourceManager.GetString("RequiredLegioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name is required  ähnelt.
        /// </summary>
        public static string RequiredNameName {
            get {
                return ResourceManager.GetString("RequiredNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Order Name is required  ähnelt.
        /// </summary>
        public static string RequiredOrdoName {
            get {
                return ResourceManager.GetString("RequiredOrdoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password is a required field. Must contain only numbers and letters and be a minimum of 5 characters. ähnelt.
        /// </summary>
        public static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password must contain no more then 20 letters or numbers. Must contain only numbers and letters and be a minimum of 5 characters ähnelt.
        /// </summary>
        public static string RequiredPassword1 {
            get {
                return ResourceManager.GetString("RequiredPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter Password ähnelt.
        /// </summary>
        public static string RequiredPassword2 {
            get {
                return ResourceManager.GetString("RequiredPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter Confirm password. ähnelt.
        /// </summary>
        public static string RequiredPassword3 {
            get {
                return ResourceManager.GetString("RequiredPassword3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm password must be same as password. ähnelt.
        /// </summary>
        public static string RequiredPassword4 {
            get {
                return ResourceManager.GetString("RequiredPassword4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Phylum Name is required  ähnelt.
        /// </summary>
        public static string RequiredPhylumName {
            get {
                return ResourceManager.GetString("RequiredPhylumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plant Species Name is required  ähnelt.
        /// </summary>
        public static string RequiredPlSpeciesName {
            get {
                return ResourceManager.GetString("RequiredPlSpeciesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference Author is required  ähnelt.
        /// </summary>
        public static string RequiredRefAuthorName {
            get {
                return ResourceManager.GetString("RequiredRefAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference Expert is required  ähnelt.
        /// </summary>
        public static string RequiredRefExpertName {
            get {
                return ResourceManager.GetString("RequiredRefExpertName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference Source is required  ähnelt.
        /// </summary>
        public static string RequiredRefSourceName {
            get {
                return ResourceManager.GetString("RequiredRefSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kingdom Name is required  ähnelt.
        /// </summary>
        public static string RequiredRegnumName {
            get {
                return ResourceManager.GetString("RequiredRegnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Role a is required field. ähnelt.
        /// </summary>
        public static string RequiredRole {
            get {
                return ResourceManager.GetString("RequiredRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Species Group Name is required  ähnelt.
        /// </summary>
        public static string RequiredSpeciesgroupName {
            get {
                return ResourceManager.GetString("RequiredSpeciesgroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sub Class Name is required  ähnelt.
        /// </summary>
        public static string RequiredSubclassName {
            get {
                return ResourceManager.GetString("RequiredSubclassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sub Division Name is required  ähnelt.
        /// </summary>
        public static string RequiredSubdivisionName {
            get {
                return ResourceManager.GetString("RequiredSubdivisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sub Family Name is required  ähnelt.
        /// </summary>
        public static string RequiredSubfamilyName {
            get {
                return ResourceManager.GetString("RequiredSubfamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sub Order Name is required  ähnelt.
        /// </summary>
        public static string RequiredSubordoName {
            get {
                return ResourceManager.GetString("RequiredSubordoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sub Phylum Name is required  ähnelt.
        /// </summary>
        public static string RequiredSubphylumName {
            get {
                return ResourceManager.GetString("RequiredSubphylumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sub Tribus Name is required  ähnelt.
        /// </summary>
        public static string RequiredSubtribusName {
            get {
                return ResourceManager.GetString("RequiredSubtribusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Super Class Name is required  ähnelt.
        /// </summary>
        public static string RequiredSuperclassName {
            get {
                return ResourceManager.GetString("RequiredSuperclassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Super Family Name is required  ähnelt.
        /// </summary>
        public static string RequiredSuperfamilyName {
            get {
                return ResourceManager.GetString("RequiredSuperfamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Super Tribus Name is required  ähnelt.
        /// </summary>
        public static string RequiredSupertribusName {
            get {
                return ResourceManager.GetString("RequiredSupertribusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Synonym is required  ähnelt.
        /// </summary>
        public static string RequiredSynonymName {
            get {
                return ResourceManager.GetString("RequiredSynonymName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tribus Name is required  ähnelt.
        /// </summary>
        public static string RequiredTribusName {
            get {
                return ResourceManager.GetString("RequiredTribusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Name is required ähnelt.
        /// </summary>
        public static string RequiredUserName {
            get {
                return ResourceManager.GetString("RequiredUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter value in the range: ähnelt.
        /// </summary>
        public static string RequiredValueRange {
            get {
                return ResourceManager.GetString("RequiredValueRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        public static string SaveQuestion {
            get {
                return ResourceManager.GetString("SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you shure to save this ? ähnelt.
        /// </summary>
        public static string SaveQuestion2 {
            get {
                return ResourceManager.GetString("SaveQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die was successfully saved ! ähnelt.
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search will be closed ähnelt.
        /// </summary>
        public static string SearchBeClosed {
            get {
                return ResourceManager.GetString("SearchBeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search Name or ID ähnelt.
        /// </summary>
        public static string SearchNameOrId {
            get {
                return ResourceManager.GetString("SearchNameOrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speciesgroup ähnelt.
        /// </summary>
        public static string Speciesgroup {
            get {
                return ResourceManager.GetString("Speciesgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die input may not be longer than 10 characters  ähnelt.
        /// </summary>
        public static string StringLength_10 {
            get {
                return ResourceManager.GetString("StringLength_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die input may not be longer than 100 characters  ähnelt.
        /// </summary>
        public static string StringLength_100 {
            get {
                return ResourceManager.GetString("StringLength_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die input may not be longer than 200 characters  ähnelt.
        /// </summary>
        public static string StringLength_200 {
            get {
                return ResourceManager.GetString("StringLength_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die input may not be longer than 300 characters  ähnelt.
        /// </summary>
        public static string StringLength_300 {
            get {
                return ResourceManager.GetString("StringLength_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die input may not be longer than 50 characters  ähnelt.
        /// </summary>
        public static string StringLength_50 {
            get {
                return ResourceManager.GetString("StringLength_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die input may not be longer than 60 characters  ähnelt.
        /// </summary>
        public static string StringLength_60 {
            get {
                return ResourceManager.GetString("StringLength_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Year must have 4 characters ähnelt.
        /// </summary>
        public static string StringLengthYear_4 {
            get {
                return ResourceManager.GetString("StringLengthYear_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subclass ähnelt.
        /// </summary>
        public static string Subclass {
            get {
                return ResourceManager.GetString("Subclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subdivision ähnelt.
        /// </summary>
        public static string Subdivision {
            get {
                return ResourceManager.GetString("Subdivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subfamily ähnelt.
        /// </summary>
        public static string Subfamily {
            get {
                return ResourceManager.GetString("Subfamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subordo ähnelt.
        /// </summary>
        public static string Subordo {
            get {
                return ResourceManager.GetString("Subordo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subphylum ähnelt.
        /// </summary>
        public static string Subphylum {
            get {
                return ResourceManager.GetString("Subphylum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subspecies ähnelt.
        /// </summary>
        public static string Subspecies {
            get {
                return ResourceManager.GetString("Subspecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subtribus ähnelt.
        /// </summary>
        public static string Subtribus {
            get {
                return ResourceManager.GetString("Subtribus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Superclass ähnelt.
        /// </summary>
        public static string Superclass {
            get {
                return ResourceManager.GetString("Superclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Superfamily ähnelt.
        /// </summary>
        public static string Superfamily {
            get {
                return ResourceManager.GetString("Superfamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Supertribus ähnelt.
        /// </summary>
        public static string Supertribus {
            get {
                return ResourceManager.GetString("Supertribus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Synonym ähnelt.
        /// </summary>
        public static string Synonym {
            get {
                return ResourceManager.GetString("Synonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tables ähnelt.
        /// </summary>
        public static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tribus ähnelt.
        /// </summary>
        public static string Tribus {
            get {
                return ResourceManager.GetString("Tribus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die try again ! ähnelt.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Profile ähnelt.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Userprofile already existing ähnelt.
        /// </summary>
        public static string UserProfileExist {
            get {
                return ResourceManager.GetString("UserProfileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Userprofile was not found ähnelt.
        /// </summary>
        public static string UserProfileNotExist {
            get {
                return ResourceManager.GetString("UserProfileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Valid ähnelt.
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The validation errors are:  ähnelt.
        /// </summary>
        public static string ValidationErrors {
            get {
                return ResourceManager.GetString("ValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Valid ähnelt.
        /// </summary>
        public static string ValidNot {
            get {
                return ResourceManager.GetString("ValidNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value must be non-zero ähnelt.
        /// </summary>
        public static string ValueNotZero {
            get {
                return ResourceManager.GetString("ValueNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value must be numeric ähnelt.
        /// </summary>
        public static string ValueNumeric {
            get {
                return ResourceManager.GetString("ValueNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
